# for people managing ZoneChecks, not used by the operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: zonecheck
    app.kubernetes.io/managed-by: kustomize
  name: zonecheck-admin-role
rules:
- apiGroups:
  - checks.zonecheck.dev
  resources:
  - zonechecks
  verbs:
  - '*'
- apiGroups:
  - checks.zonecheck.dev
  resources:
  - zonechecks/status
  verbs:
  - get
